name: KMP build for Android

on:
  workflow_run:
    workflows: [ "Create Release" ]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create Local properties
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" > local.properties

      - name: Generate BuildKonfig
        run: ./gradlew generateBuildKonfig

      - name: Decode Keystore
        run: | 
          echo "${{ secrets.KEYSTORE }}" | base64 -d > composeApp/my-release-key.keystore

      - name: Generate Signed apk
        run: ./gradlew assembleRelease

      - name: Get Release Upload URL
        id: get_upload_url
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            core.setOutput("upload_url", release.upload_url);

      - name: Upload to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url.outputs.upload_url }}
          asset_path: composeApp/build/outputs/apk/release/composeApp-release.apk
          asset_name: TorrServerMedia.apk
          asset_content_type: application/octet-stream