name: KMP build Desktop

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build AppImage
        run: ./gradlew packageAppImage

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#jobs:
#  build_desktop:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest]
#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v4
#
#      - name: Build Desktop App
#        uses: openMF/kmp-build-desktop-app-action@v1.0.0
#        with:
#          desktop_package_name: 'TorrServerMedia'