name: KMP build Desktop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for Gradlew
        run: chmod +x gradlew

      - name: Build package for Linux
        run: ./gradlew packageUberJarForCurrentOS

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: compose-linux-uber-jar
          path: build/libs/*.jar
